version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - vendor: Statens pensjonskasse
    homepage: https://github.com/statens-pensjonskasse/jencli
    maintainer: Statens pensjonskasse
    description: |-
      Bitbucket API CLI client written in Go.
    license: MIT
    formats:
      - deb
      - rpm

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
