package types

const (
	ConfigFlag                          = "config"
	ContextFlag                         = "context"
	ContextFlagShorthand                = "x"
	GitUrlFlag                          = "git-url"
	BaseUrlFlag                         = "base-url"
	LimitFlag                           = "limit"
	LimitFlagShorthand                  = "l"
	TokenFlag                           = "token"
	TokenFlagShorthand                  = "t"
	OutputFlag                          = "output"
	OutputFlagShorthand                 = "o"
	ProjectKeyFlag                      = "project"
	ProjectKeyFlagShorthand             = "p"
	RepoSlugFlag                        = "repo"
	RepoSlugFlagShorthand               = "r"
	IncludeReposFlag                    = "include-repos"
	IncludeArchivedFlag                 = "include-archived"
	IncludeArchivedFlagShorthand        = "a"
	UpdateFlag                          = "update"
	UpdateFlagShorthand                 = "u"
	ForceFlag                           = "force"
	ForceFlagShorthand                  = "F"
	FilenameFlag                        = "file"
	FilenameFlagShorthand               = "f"
	PullRequestTitleFlag                = "title"
	PullRequestTitleFlagShorthand       = "T"
	PullRequestDescriptionFlag          = "description"
	PullRequestDescriptionFlagShorthand = "d"
	PullRequestReviewerFlag             = "reviewer"
	PullRequestReviewerFlagShorthand    = "w"
	PullRequestFromBranchFlag           = "from-branch"
	PullRequestToBranchFlag             = "to-branch"
	NoDefaultReviewersFlag              = "no-default-reviewers"
)
